// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq0wzk-s4Zj8GiY_Ndj5CctJSl_3kBJ0s',
    appId: '1:734074238844:web:56e41a325c5f1728f856f9',
    messagingSenderId: '734074238844',
    projectId: 'whoops-capnap-eyepatch',
    authDomain: 'whoops-capnap-eyepatch.firebaseapp.com',
    storageBucket: 'whoops-capnap-eyepatch.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeHL_nRvrgoIN0P0fvjZUcimi0tnC9_Jw',
    appId: '1:734074238844:android:f0708c7d083472e3f856f9',
    messagingSenderId: '734074238844',
    projectId: 'whoops-capnap-eyepatch',
    storageBucket: 'whoops-capnap-eyepatch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk-HvatkIMVboi-yfBwvqoMfPfyTaGGMs',
    appId: '1:734074238844:ios:cc667e59fd29bedff856f9',
    messagingSenderId: '734074238844',
    projectId: 'whoops-capnap-eyepatch',
    storageBucket: 'whoops-capnap-eyepatch.appspot.com',
    iosClientId: '734074238844-n7otji02aq2iv8b75347dh9g7hbdmk0b.apps.googleusercontent.com',
    iosBundleId: 'com.capnap.whoops4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk-HvatkIMVboi-yfBwvqoMfPfyTaGGMs',
    appId: '1:734074238844:ios:3423a51ffc068033f856f9',
    messagingSenderId: '734074238844',
    projectId: 'whoops-capnap-eyepatch',
    storageBucket: 'whoops-capnap-eyepatch.appspot.com',
    iosClientId: '734074238844-o469dto8p6poolljt3bhfr5rkdbd8ef7.apps.googleusercontent.com',
    iosBundleId: 'com.capnap.whoops4.RunnerTests',
  );
}
